refactor: rewrite all commands
CurseHosting/bot pull request #18
Opened 2020-08-25 17:07 UTC by mestery69

2020-08-25 17:46 UTC, ZeProf2Code requested changes

2020-08-25 17:46 UTC, ZeProf2Code commented on bot.js
> -// This will check if the node version you are running is the required
Please do not rename bot.js and index.js.

2020-08-25 17:46 UTC, ZeProf2Code commented on commands/close.js
> +  const m = await client.info('Vous êtes sûr ? Une fois confirmée, vous ne pourrez pas annuler cette action !\nPour confirmer, réagissez à "✅". Pour annuler, réagissez à "❌". Cette action sera annulé
"réagisssez avec"

2020-08-25 17:46 UTC, ZeProf2Code commented on commands/close.js
> +      logsChannel.send(output + messagesText)
2000 characters limit, please.

2020-08-25 17:46 UTC, ZeProf2Code commented on commands/register.js
> +      message.channel.send('temps écoulée') // timeout.
':alarm_clock: Temps écoulé.'

2020-08-25 17:46 UTC, ZeProf2Code commented on commands/stats.js
> +Utilisation CPU : 0.0%`) // 0.0% hmmmm
héhé, c'était la flemme de récupérer l'utilisation du CPU x)

2020-08-25 17:46 UTC, ZeProf2Code commented on commands/unregister.js
> +  client.error('Désolé mais cette commande n\'est pas encore disponible.') // command not ready
Yeah, delete it directly 👍

2020-08-25 17:46 UTC, ZeProf2Code commented on index.js
> -const { ShardingManager } = require('discord.js');
don't rename index.js and bot.js

2020-08-25 17:46 UTC, ZeProf2Code commented on shard.js
> +const { join } = require('path')
don't rename index.js and bot.js

2020-08-26 00:18 UTC, mestery69 commented on bot.js
> -// This will check if the node version you are running is the required
Why ?

2020-08-26 00:20 UTC, mestery69 commented on commands/stats.js
> +Utilisation CPU : 0.0%`) // 0.0% hmmmm
😅 la flemme nous domine x)

2020-08-26 00:25 UTC, mestery69 commented
For 2000 characters limit, it's unnecessary, because discord message characters limit is already 2000, so you can't receive a message with more than 2000 characters :)

2020-08-26 00:25 UTC, mestery69 commented on commands/unregister.js
> +  client.error('Désolé mais cette commande n\'est pas encore disponible.') // command not ready
Delete the file ?

2020-08-26 00:28 UTC, mestery69 commented on commands/close.js
> +      logsChannel.send(output + messagesText)
it's unnecessary, because discord message characters limit is already 2000, so you can't receive a message with more than 2000 characters :)

2020-08-26 00:31 UTC, mestery69 commented on index.js
> -const { ShardingManager } = require('discord.js');
delete the file ?

2020-08-26 00:32 UTC, mestery69 commented on commands/unregister.js
> +  client.error('Désolé mais cette commande n\'est pas encore disponible.') // command not ready
delete the file ?

2020-08-26 06:29 UTC, ZeProf2Code commented on commands/unregister.js
> +  client.error('Désolé mais cette commande n\'est pas encore disponible.') // command not ready
no, delete the API key.

2020-08-26 06:29 UTC, ZeProf2Code commented on commands/close.js
> +      logsChannel.send(output + messagesText)
no, it will not send all the tickets message because of this.

2020-08-26 06:33 UTC, ZeProf2Code commented on bot.js
> -// This will check if the node version you are running is the required
because I want to keep these ¯\_(ツ)_/¯

2020-08-26 06:35 UTC, merged